version: "3"
services:
    frontend:
        build: ./frontend
        image: gidsi/spaceapi-ccc-frontend:latest
        depends_on:
            - backend
    backend:
        build: ./backend
        image: gidsi/spaceapi-ccc-backend:latest
        env_file: .env
        depends_on:
            - database
    database:
        image: mongo:latest
        volumes:
            - /opt/eva:/data/db
